### ISSUE TITLE
add array not showing last element

### ISSUE THREAD

**Issue by hayden-t** [frankforte/quantumphp#2]
So it just seems to be not showing the last element of my arrays. They are there if i var_dump but not in the console from quantum...

**Comment by frankforte** [comment]
The following works for me:

```PHP
<?php
    $arr = [1,2,3,4,5,6,7,8,9];
    $arr2 = ["a","b","c","d","e"];
    $arr3 = ["a"=>"one","b"=>"two","c"=>"three","d"=>"four","e"=>"five"];

    QuantumPHP::add($arr);
    sleep(1);
    QuantumPHP::add($arr2);
    sleep(1);
    QuantumPHP::add($arr3);
    QuantumPHP::send();
    exit;
```
`sleep(1);` is not required. I only added it to double check that the time column was working (without sleep, the script runs in "0" seconds - this is a limitation with precision when a script is very short/fast).

![Console Example](https://github.com/frankforte/quantumphp/blob/master/docs/quantumphp-test.png?raw=true)
