### ISSUE TITLE
Simply does not work

### ISSUE THREAD

**Issue by versussoft** [frankforte/quantumphp#3]
I have followed the instructions and none appear on Firefox console with QuantumPHP extension or Chrome console with ChromePHP extension
* I use Firefox 57.0.2, Apache 2.22 and PHP 5.6.32
* Quantum extension is loaded and browser restarted
* I put include of QuantumPHP.php at start of php file,  php run normally and the html output is fine
* None output appear in Firefox console . Either none X-ChromeLogger-Data header appear in Firefox Console Network
What happens?

**Comment by frankforte** [comment]
I would be happy to help you get QuantumPHP working. It has been working
well for me on both windows iis and apache, both php 5.6 and 7.0.

SOME THINGS TO DOUBLE CHECK:

1) Does the php error log have any hints? If it complains about trying to
send headers, when output has already been sent, try a different mode, for
example:

QuantumPHP::$MODE = 0;

This should be done before you run this:

QuantumPHP::send();


2) Have you tried a simple PHP file without your code, to see if you can
get debug output in the Firefox console? It could be that your code never
calls send().

3) do you have the correct output showing in the Firefox console? You can
turn on and off warnings and errors for HTTP, JavaScript, CSS, etc. Make
sure you turn the HTTP and JavaScript warnings and errors onI your browser.

If there is a bug, I hope you will help me find it. Please understand
that things have changed, so it could take a bit of effort to get it
working. I'm sure it will be worth the time.

**Comment by versussoft** [comment]
Sorry, i expected a like FirePHP  behaviour and i miss to  insert QuantumPHP::send(); at the end of code. 
Now work perfectly!    👍 
Thanks for allow debugging using Firefox Quantum!
