### ISSUE TITLE
Bug with Output Buffering

### ISSUE THREAD

**Issue by jeeba** [frankforte/quantumphp#7]
I tried QuantumPHP and it worked like a charm if I put your code at the start of my code, like in my config.php that run at the start of all.

But when I put it at the end of all the code it didnt work. What I discovered is that it have something to do with ouput_buffering. I discovered that if I change my default 4096 to something more it will appear. 

It was funny, I deleted some HTML code and it was working, I added a little more code and it stopped working. So after a lot of trial an error, and changing output_buffering because of a comment in your code I managed to make it work.

Also, I dont need your Javascript file to send the info in Firefox Quantum, It's that ok?

**Comment by frankforte** [comment]
Unless you use mode 0, the log is sent in the HTTP headers. This means you
must run the send() method before you echo any content.

You can get around this (you can add debug statements in your HTML) by
using output buffering. Here is an example:


ob_start();

echo "html content";

QuantumPHP::add('Hello console table!');

$html = ob_get_flush();

QuantumPHP::send();

echo $html;
